spring.application.name=contable

# 1. URL (con el servidor us-east-2 de tu cadena y prepareThreshold=0 para el pooler)
spring.datasource.url=jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:5432/postgres?prepareThreshold=0

# 2. Usuario (extra\u00eddo de lo que va antes de los dos puntos)
spring.datasource.username=postgres.qxwczjyidvymqzhahfsd

# 3. Contrase\u00f1a (escribe tu contrase\u00f1a real aqu\u00ed, sin corchetes)
spring.datasource.password=Dantex1200!.

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true